### PR TITLE
Introduce React via Footer component

### PR DESCRIPTION
**Pull request by rachelruderman**
**Description**
This PR is the first step in gradually introducing React to the frontend. 

It replaces the `footer` HTML with the `<Footer/>` React component in the following files:
- `landing.html`
- `newcall.html`
- `notsupported.html`
- `notsupportedios.html`

Once all the pieces have been rewritten in React, we can migrate to `create-react-app`. 

**How to Test**
- [ ] Start the server by running `npm start`
- [ ] Navigate to `localhost:3000`, scroll down to the footer, and inspect element.
- [ ] Confirm the footer is wrapped in a div with the id `react-footer-container`
Screen Shot 2020-07-03 at 1 29 58 AM
- [ ] Confirm all the links are functional
- [ ] Repeat on http://localhost:3000/newcall
- [ ] Repeat on http://localhost:3000/notsupported
- [ ] Repeat on http://localhost:3000/notsupportedios

### CODE REVIEW

**Comment by Chaphasilor** [comment]
why should the app be converted to react?

**Comment by rachelruderman** [comment]
> why should the app be converted to react?

Hi!! I found out about this project via Ian's [interview with Syntax.fm](https://syntax.fm/show/256/webrtc-and-peer-to-peer-video-calling-with-ian-ramzy). At minute 16:37 he says, "My one regret is that I didn't make the application in React" 😄  

Apparently JQuery was good for getting things up and running fast, but caused some ugly solutions for state management

**Comment by Chaphasilor** [comment]
well if @ianramzy wants this to be a react app, I guess it's nice that you stared working on it :)

**Comment by rachelruderman** [comment]
@ianramzy is this something you’re interested in? If so, I’ll keep going! If not, I’ll close out the PR :)

**Comment by ianramzy** [comment]
Hey sorry for the delay in getting back to you. I actually already have all the landing pages of the app built in React. The challenging part is the actual chat.html. So if you would like to rebuild that in React, that would be super helpful. Thanks :)

**Comment by rachelruderman** [comment]
> Hey sorry for the delay in getting back to you. I actually already have all the landing pages of the app built in React. The challenging part is the actual chat.html. So if you would like to rebuild that in React, that would be super helpful. Thanks :)

Cool, I’m down for that!!

**Comment by rachelruderman** [comment]
@ianramzy is there a React branch I can fork from? Thanks!

**Pull request closed without merging**
