### PR TITLE
adds a refresh room name button to the new call page

### PR DESCRIPTION
**Pull request by reed-jones**
A small thing, but I found myself refreshing the page trying to get a the 'right' room name.

Screen Shot 2020-06-13 at 8 51 38 AM

### CODE REVIEW

**Comment by Chaphasilor** [comment]
I think the wording of the button could be improved, maybe something like 'Suggest another name' (prefferably shorter)?

Refresh is a bit ambiguous and not that exciting :)

Apart from that, I like the idea :D

**Comment by reed-jones** [comment]
Thanks! I totally agree. I was thinking some sort of 'retry/rename/refresh' icon or something might be better instead of text too? That might make more sense since then it would be smaller & not so attention grabbing since the 'Go To My Call' really is the main button people will click here.

The other thing I have seen elsewhere is the room name just auto refreshing on a timer every X seconds

**Comment by Chaphasilor** [comment]
> I was thinking some sort of 'retry/rename/refresh' icon or something might be better instead of text too?
That is a great idea! You could also try positioning it away from the 'Go to call' button and closer to the actual room name :)

> The other thing I have seen elsewhere is the room name just auto refreshing on a timer every X seconds
Ahh, I don't like it. If you don't like the room name you'd have to wait and if you like it you are under pressure to start the call :/

**Comment by ianramzy** [comment]
I appreciate the pull request, however I do not want to add more buttons to the UI, I will not be merging this in. I hope you understand :)

**Pull request closed without merging**
