### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by RoyceAroc**
This pull request adds a `Run on Repl.it` badge to the `README`. This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

### CODE REVIEW

**Comment by Chaphasilor** [comment]
Wait, isn't there now native support from GitHub for this? Using a browser-based VS Code instance?

**Comment by RoyceAroc** [comment]
Yeah VS will surely help. I'm too lazy to use VS so I'm using Repl's IDE to host the server.

**Comment by ianramzy** [comment]
Add the badge after all the other badges and Ill merge it in.

**Comment by Chaphasilor** [comment]
I'll close this because the fork doesn't exist anymore...
@RoyceAroc if you still want this, just open another PR (with the badge after all the other ones) and I'll merge it, given that @ianramzy already said he's okay with it...

**Pull request closed without merging**
