### PR TITLE
Mobile CSS

### PR DESCRIPTION
**Pull request by Chaphasilor**
- working portrait mode for phones
- removed 'not supported' alert for Android, left the others for now
- landscape mode is not working yet due to missing initial-scale meta tag

### CODE REVIEW

**Comment by ianramzy** [comment]
Just did some basic testing of the PR and I don't think it is quite ready. But it is lookin good!

1. The share screen and picture in picture buttons need to be removed
2. If you change the width of your desktop browser too small then it messes up, and more importantly, It doesn't fix itself back to the normal desktop UI when expanded
3. The Type a message input should be the full width of the screen when shown.
4. Make sure you run your code through Prettier before you PR :) instructions here: https://prettier.io/

**Comment by Chaphasilor** [comment]
> 1. The share screen and picture in picture buttons need to be removed 

Yeah I didn't remove anything just yet, but will do!

> 2. If you change the width of your desktop browser too small then it messes up, and more importantly, It doesn't fix itself back to the normal desktop UI when expanded 

Hmm, that doesn't happen for me. What are you testing with?  
The messed up UI is caused by jQuery's fade effeczs, I'll replace that today. 

> 3. The Type a message input should be the full width of the screen when shown.

I made the input be the size of the chat and have the chat right aligned, should I expand it to the whole screen width as well?

> 4. Make sure you run your code through Prettier before you PR :) instructions here: https://prettier.io/

Okay sure if you want to :)

**Comment by Chaphasilor** [comment]
Would you mind adding a new script to package.json to apply prettier to all files with your preferred config?

So that we could do `npm run prettify` or something similar?

**Comment by Chaphasilor** [comment]
> Just did some basic testing of the PR and I don't think it is quite ready.

How about now?  
The only thing I'm not sure about is your issue in 2. where the layout doesn't switch back on resizing, but for me it is and has always been working fine...

**Pull request merged**
